quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.headers=accept, authorization, content-type, origin

# JWT Configuration
# JWT Configuration
mp.jwt.verify.issuer=https://wordle.climb
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem

# H2 File database configuration (keeps data saved in the project directory)
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:file:./db/wordledb;DB_CLOSE_DELAY=-1
quarkus.datasource.username=sa
quarkus.datasource.password=sa

# Automatically update the database tables based on our Java Entity models
quarkus.hibernate-orm.database.generation=update
# Log generated SQL to the console so we can see what Hibernate does behind the scenes (great for learning!)
quarkus.hibernate-orm.log.sql=true

# LangChain4j Groq AI configuration
quarkus.langchain4j.openai.base-url=https://api.groq.com/openai/v1
quarkus.langchain4j.openai.api-key=${GROQ_API_KEY:DEMO_KEY}
quarkus.langchain4j.openai.chat-model.model-name=llama-3.1-8b-instant

# Redis & Cache Configuration
%dev.quarkus.redis.hosts=redis://localhost:6379
quarkus.cache.redis.leaderboard.expire-after-write=10M

# OpenAPI Configuration
quarkus.swagger-ui.always-include=true
# Use in-memory DB for tests to prevent locking the file DB when dev mode is running
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb
%test.quarkus.hibernate-orm.database.generation=drop-and-create

# --- PRODUCTION CONFIGURATION ---
# Database
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.jdbc.url=${DATABASE_URL}
%prod.quarkus.datasource.username=${DATABASE_USER}
%prod.quarkus.datasource.password=${DATABASE_PASSWORD}
%prod.quarkus.hibernate-orm.database.generation=update
# %prod.quarkus.flyway.migrate-at-start=true

# Security & API Keys
%prod.smallrye.jwt.sign.key.location=${JWT_PRIVATE_KEY_PATH}
%prod.mp.jwt.verify.publickey.location=${JWT_PUBLIC_KEY_PATH}
%prod.quarkus.langchain4j.openai.api-key=${GROQ_API_KEY}
%prod.quarkus.redis.hosts=redis://redis:6379

# CORS
%prod.quarkus.http.cors.origins=${CORS_ORIGINS:*}

# Logging (Structured JSON for Production)
%prod.quarkus.log.console.json=true
%prod.quarkus.log.console.json.pretty-print=false

